# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58f8c22d829bc163b4ed340f70bb3fdf3c650498f2e6744ae2d6669cdc6290decc1c9b8d49cd3a6b7763226a97cafd5638ede2b5fa9dfa3b74727b6a5cb928de

test:
  secret_key_base: 32b3c56d19bd50e2afc5613bce06898610a607ef67e45692be391f94db31242de1c6f3876ecf58a9ce64fb0e2980deaad66aef79a906f855dc99142a0a0f6944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
